[Annotation issues at runtime](https://mypy.readthedocs.io/en/stable/runtime_troubles.html)
